import { useEffect, useMemo, useState } from 'react';
import type { ToolApiClient } from '../api/tool-api';
import type { ToolSummaryDto } from '../api/types';
const scope = { tenantId: 'local', workspaceId: 'default' } as const;
export function SkillBuilder({ client }: { readonly client: ToolApiClient }) {
  const [tools, setTools] = useState<readonly ToolSummaryDto[]>([]); const [selected, setSelected] = useState<ReadonlySet<string>>(new Set());
  const [internalId, setInternalId] = useState('data-analysis'); const [workingName, setWorkingName] = useState('Data analysis draft');
  const [displayName, setDisplayName] = useState('Data analysis'); const [publishName, setPublishName] = useState('data_analysis'); const [owner, setOwner] = useState('local-user');
  const [responsibility, setResponsibility] = useState('Analyze supplied data with deterministic tools.');
  const [activationCondition, setActivationCondition] = useState('Use when the user asks to inspect or summarize structured data.');
  const [inputDescription, setInputDescription] = useState('A user request and the data needed for analysis.');
  const [outputDescription, setOutputDescription] = useState('A concise answer grounded in Tool results.');
  const [instructions, setInstructions] = useState('Use the selected tools only when their contracts match the request.');
  const [savedVersion, setSavedVersion] = useState<string>(); const [busy, setBusy] = useState(false); const [error, setError] = useState<string>();
  useEffect(() => { let active = true; void client.listTools(scope).then((items) => { if (active) setTools(items); }).catch((cause: unknown) => { if (active) setError(message(cause)); }); return () => { active = false; }; }, [client]);
  const refs = useMemo(() => tools.filter((tool) => selected.has(key(tool))).map((tool) => ({ internalId: tool.internalId, version: tool.latestVersion })), [selected, tools]);
  const promptInput = { scope, displayName, responsibility, activationCondition, inputDescription, outputDescription, tools: refs };
  function toggle(tool: ToolSummaryDto) { const id = key(tool); setSelected((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; }); }
  async function generate() { setBusy(true); setError(undefined); try { setInstructions((await client.generateSkillPrompt(promptInput)).promptDraft); } catch (cause) { setError(message(cause)); } finally { setBusy(false); } }
  async function save() { setBusy(true); setError(undefined); try { const skill = await client.saveSkill({ ...promptInput, internalId, workingName, publishName, owner, instructions }); setSavedVersion(skill.metadata.version); } catch (cause) { setError(message(cause)); } finally { setBusy(false); } }
  return <main className="agent-builder"><header className="agent-builder-header"><div><span className="eyebrow">Skill Builder</span><h1>{displayName}</h1><p>責務・発火条件・Tool依存から再利用可能なSkillを定義します。</p></div><div className="save-actions">{savedVersion !== undefined && <span className="version-chip">saved {savedVersion}</span>}<button className="secondary" type="button" disabled={busy} onClick={() => void generate()}>Generate draft</button><button className="primary" type="button" disabled={busy || instructions.trim() === ''} onClick={() => void save()}>Save version</button></div></header>{error !== undefined && <div className="api-error">{error}</div>}<div className="agent-builder-grid"><section className="agent-definition-card"><h2>Definition</h2><div className="agent-fields"><label>Internal ID<input aria-label="Skill internal ID" value={internalId} onChange={(event) => setInternalId(event.target.value)} /></label><label>Working name<input value={workingName} onChange={(event) => setWorkingName(event.target.value)} /></label><label>Display name<input aria-label="Skill display name" value={displayName} onChange={(event) => setDisplayName(event.target.value)} /></label><label>Publish name<input value={publishName} onChange={(event) => setPublishName(event.target.value)} /></label><label>Owner<input value={owner} onChange={(event) => setOwner(event.target.value)} /></label></div><label>Responsibility<textarea aria-label="Skill responsibility" rows={3} value={responsibility} onChange={(event) => setResponsibility(event.target.value)} /></label><label>Activation condition<textarea aria-label="Skill activation condition" rows={3} value={activationCondition} onChange={(event) => setActivationCondition(event.target.value)} /></label><label>Input description<textarea rows={2} value={inputDescription} onChange={(event) => setInputDescription(event.target.value)} /></label><label>Output description<textarea rows={2} value={outputDescription} onChange={(event) => setOutputDescription(event.target.value)} /></label><h2>Tools <small>{refs.length} selected</small></h2><div className="agent-tool-list">{tools.length === 0 && <p className="empty-state">保存済みToolがありません。</p>}{tools.map((tool) => <label key={key(tool)} className="agent-tool-option"><input type="checkbox" checked={selected.has(key(tool))} onChange={() => toggle(tool)} /><span><strong>{tool.displayName}</strong><code>{tool.publishName}@{tool.latestVersion}</code></span></label>)}</div></section><section className="prompt-editor-card"><div className="panel-title"><div><span className="eyebrow">Editable escape hatch</span><h2>Skill instructions</h2></div><span className="version-chip">{instructions.length} chars</span></div><textarea aria-label="Skill instructions" rows={34} value={instructions} onChange={(event) => setInstructions(event.target.value)} /></section></div></main>;
}
function key(tool: ToolSummaryDto) { return `${tool.internalId}@${tool.latestVersion}`; }
function message(cause: unknown) { return cause instanceof Error ? cause.message : 'Request failed'; }
