import { useEffect, useState } from 'react';
import type { ToolApiClient } from '../api/tool-api';
import type { AgentSummaryDto } from '../api/types';

const scope = { tenantId: 'local', workspaceId: 'default' } as const;
interface Result { readonly passed: boolean; readonly runId: string; readonly observed: readonly string[]; readonly response: string }
export function ValidationPage({ client }: { readonly client: ToolApiClient }) {
  const [agents, setAgents] = useState<readonly AgentSummaryDto[]>([]); const [agentId, setAgentId] = useState('');
  const [scenario, setScenario] = useState('Answer the request using the appropriate Tool.'); const [expectedTool, setExpectedTool] = useState('');
  const [result, setResult] = useState<Result>(); const [busy, setBusy] = useState(false); const [error, setError] = useState<string>();
  useEffect(() => { let active = true; void client.listAgents(scope).then((items) => { if (active) { setAgents(items); setAgentId(items[0]?.internalId ?? ''); } }).catch((cause: unknown) => { if (active) setError(cause instanceof Error ? cause.message : 'Request failed'); }); return () => { active = false; }; }, [client]);
  async function validate() { const agent = agents.find((item) => item.internalId === agentId); if (agent === undefined) return; setBusy(true); setError(undefined); setResult(undefined); try { const run = await client.runSavedAgent({ scope, agent: { internalId: agent.internalId, version: agent.latestVersion }, message: scenario, mode: 'test' }); const observed = (run.tools ?? (run.tool === undefined ? [] : [run.tool])).map((tool) => tool.publishName ?? tool.internalId); const expected = expectedTool.trim(); setResult({ passed: expected === '' ? true : observed.includes(expected), runId: run.runId, observed, response: run.response }); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Request failed'); } finally { setBusy(false); } }
  return <main className="workspace-page"><header className="workspace-header"><div><span className="eyebrow">Validation</span><h1>Scenario validation</h1><p>保存済みAgentをtest modeで実行し、期待Toolと実際の呼び出しを照合します。</p></div></header>{error !== undefined && <div className="api-error">{error}</div>}<div className="two-column-workspace"><section className="workspace-card"><label>Target agent<select aria-label="Validation agent" value={agentId} onChange={(event) => setAgentId(event.target.value)}><option value="">Select an agent</option>{agents.map((agent) => <option value={agent.internalId} key={agent.internalId}>{agent.displayName} · {agent.latestVersion}</option>)}</select></label><label>Scenario<textarea aria-label="Validation scenario" rows={7} value={scenario} onChange={(event) => setScenario(event.target.value)} /></label><label>Expected Tool publish name<input aria-label="Expected tool" value={expectedTool} placeholder="Optional" onChange={(event) => setExpectedTool(event.target.value)} /></label><button type="button" className="primary" disabled={busy || agentId === '' || scenario.trim() === ''} onClick={() => void validate()}>{busy ? 'Validating…' : 'Run validation'}</button></section><section className="workspace-card" aria-label="Validation result"><h2>Result</h2>{result === undefined ? <p className="empty-state">検証結果がここに表示されます。</p> : <div className={`validation-result ${result.passed ? 'passed' : 'failed'}`}><strong>{result.passed ? 'PASS' : 'FAIL'}</strong><code>{result.runId}</code><p>Observed Tools: {result.observed.join(', ') || 'none'}</p><p>{result.response}</p></div>}</section></div></main>;
}
