import { z } from 'zod';
import type { Row, Schema, Table } from '../../data/types';
import { ConfigError } from '../errors';
import type { EtlNode, SchemaInference, SchemaIssue } from '../node';
import { zodMessage } from './zod-error';
import { numericColumns, requireNumbers } from './analysis-utils';

export interface CorrelationAnalysisConfig { readonly configVersion: 1; readonly columns: readonly string[]; readonly method: 'pearson' | 'spearman'; readonly missing: 'pairwise' | 'listwise'; readonly minPairs: number; readonly includeDiagonal: boolean; }
const configSchema = z.object({ configVersion: z.literal(1).default(1), columns: z.array(z.string().min(1)).min(2).max(30), method: z.enum(['pearson', 'spearman']).default('pearson'), missing: z.enum(['pairwise', 'listwise']).default('pairwise'), minPairs: z.number().int().min(2).max(100000).default(2), includeDiagonal: z.boolean().default(false) });
const output: Schema = { columns: [{ name: 'columnX', type: 'string', nullable: false }, { name: 'columnY', type: 'string', nullable: false }, { name: 'coefficient', type: 'number', nullable: true }, { name: 'absoluteCoefficient', type: 'number', nullable: true }, { name: 'pairCount', type: 'number', nullable: false }, { name: 'method', type: 'string', nullable: false }] };
function validate(config: unknown): CorrelationAnalysisConfig { const parsed = configSchema.safeParse(config); if (!parsed.success) throw new ConfigError(`correlation-analysis: invalid config: ${zodMessage(parsed.error)}`); return parsed.data; }
function ranks(values: readonly number[]): number[] { const indexed = values.map((value, index) => ({ value, index })).sort((a, b) => a.value - b.value); const result = new Array<number>(values.length); for (let start = 0; start < indexed.length;) { let end = start + 1; while (end < indexed.length && indexed[end]?.value === indexed[start]?.value) end++; const rank = (start + 1 + end) / 2; for (let i = start; i < end; i++) { const item = indexed[i]; if (item !== undefined) result[item.index] = rank; } start = end; } return result; }
function pearson(left: readonly number[], right: readonly number[]): number | null { if (left.length < 2) return null; const lx = left.reduce((sum, value) => sum + value, 0) / left.length; const ry = right.reduce((sum, value) => sum + value, 0) / right.length; let numerator = 0; let a2 = 0; let b2 = 0; for (let i = 0; i < left.length; i++) { const a = left[i]! - lx; const b = right[i]! - ry; numerator += a * b; a2 += a * a; b2 += b * b; } return a2 === 0 || b2 === 0 ? null : numerator / Math.sqrt(a2 * b2); }
export const correlationAnalysisNode: EtlNode<CorrelationAnalysisConfig> = {
  type: 'correlation-analysis', kind: 'analyze', inputArity: 1, validateConfig: validate,
  inferSchema(inputs, config): SchemaInference { const input = inputs[0] ?? { columns: [] }; const issues: SchemaIssue[] = numericColumns(input, config.columns, 'correlation-analysis'); return issues.length > 0 ? { schema: input, state: 'mismatch', issues } : { schema: output, state: 'confirmed', issues: [] }; },
  execute(inputs, config): Table { const input = inputs[0]; if (input === undefined) throw new ConfigError('correlation-analysis requires one input'); requireNumbers(input.schema, config.columns, 'correlation-analysis'); const rows: Row[] = []; const listwise = config.missing === 'listwise' ? input.rows.filter((row) => config.columns.every((column) => typeof row[column] === 'number' && Number.isFinite(row[column] as number))) : input.rows;
    for (let x = 0; x < config.columns.length; x++) for (let y = x + (config.includeDiagonal ? 0 : 1); y < config.columns.length; y++) { const columnX = config.columns[x]!; const columnY = config.columns[y]!; const pairs = listwise.flatMap((row) => { const left = row[columnX]; const right = row[columnY]; return typeof left === 'number' && Number.isFinite(left) && typeof right === 'number' && Number.isFinite(right) ? [[left, right] as const] : []; }); const left = pairs.map((pair) => pair[0]); const right = pairs.map((pair) => pair[1]); const raw = pairs.length < config.minPairs ? null : config.method === 'spearman' ? pearson(ranks(left), ranks(right)) : pearson(left, right); rows.push({ columnX, columnY, coefficient: raw, absoluteCoefficient: raw === null ? null : Math.abs(raw), pairCount: pairs.length, method: config.method }); }
    return { schema: output, rows }; },
};
