import { z } from 'zod';
import type { Column, Row, Schema, Table } from '../../data/types';
import { ConfigError } from '../errors';
import type { EtlNode, SchemaInference, SchemaIssue } from '../node';
import { zodMessage } from './zod-error';
import { existingColumns, groupKey, numericColumns, quantile, requireColumns, requireNumbers, standardDeviation, mean } from './analysis-utils';

export interface OutlierFilterConfig { readonly configVersion: 1; readonly columns: readonly string[]; readonly groupBy: readonly string[]; readonly method: 'iqr' | 'z-score' | 'mad'; readonly threshold: number; readonly action: 'flag' | 'exclude'; readonly nulls: 'keep' | 'exclude'; readonly flagColumns: { readonly isOutlier: string; readonly score: string; readonly reason: string }; }
const configSchema = z.object({ configVersion: z.literal(1).default(1), columns: z.array(z.string().min(1)).min(1).max(20), groupBy: z.array(z.string().min(1)).default([]), method: z.enum(['iqr', 'z-score', 'mad']).default('iqr'), threshold: z.number().positive().max(100).default(1.5), action: z.enum(['flag', 'exclude']).default('flag'), nulls: z.enum(['keep', 'exclude']).default('keep'), flagColumns: z.object({ isOutlier: z.string().min(1).default('isOutlier'), score: z.string().min(1).default('outlierScore'), reason: z.string().min(1).default('outlierReason') }).default({ isOutlier: 'isOutlier', score: 'outlierScore', reason: 'outlierReason' }) });
function validate(config: unknown): OutlierFilterConfig { const parsed = configSchema.safeParse(config); if (!parsed.success) throw new ConfigError(`outlier-filter: invalid config: ${zodMessage(parsed.error)}`); return parsed.data; }
function outputSchema(input: Schema, config: OutlierFilterConfig): Schema { if (config.action === 'exclude') return input; const names = new Set(input.columns.map((column) => column.name)); const added: Column[] = [{ name: config.flagColumns.isOutlier, type: 'boolean', nullable: false }, { name: config.flagColumns.score, type: 'number', nullable: true }, { name: config.flagColumns.reason, type: 'string', nullable: true }]; return { columns: [...input.columns, ...added.filter((column) => !names.has(column.name))] }; }
type Bounds = { readonly low: number; readonly high: number; readonly center: number; readonly scale: number };
function bounds(values: readonly number[], config: OutlierFilterConfig): Bounds | undefined { if (values.length === 0) return undefined; if (config.method === 'iqr') { const q1 = quantile(values, .25); const q3 = quantile(values, .75); if (q1 === null || q3 === null) return undefined; const iqr = q3 - q1; return { low: q1 - config.threshold * iqr, high: q3 + config.threshold * iqr, center: 0, scale: 0 }; } const center = config.method === 'mad' ? quantile(values, .5) : mean(values); const raw = config.method === 'mad' && center !== null ? quantile(values.map((value) => Math.abs(value - center)), .5) : standardDeviation(values, 'population'); const scale = config.method === 'mad' && raw !== null ? raw * 1.4826 : raw; return center === null || scale === null ? undefined : { low: center, high: center, center, scale }; }
export const outlierFilterNode: EtlNode<OutlierFilterConfig> = {
  type: 'outlier-filter', kind: 'analyze', inputArity: 1, validateConfig: validate,
  inferSchema(inputs, config): SchemaInference { const input = inputs[0] ?? { columns: [] }; const issues: SchemaIssue[] = [...existingColumns(input, config.groupBy, 'outlier-filter'), ...numericColumns(input, config.columns, 'outlier-filter')]; const outputNames = new Set(input.columns.map((column) => column.name)); if (config.action === 'flag') for (const name of Object.values(config.flagColumns)) if (outputNames.has(name)) issues.push({ severity: 'error', message: `outlier-filter: flag column already exists: ${name}`, column: name }); return issues.length > 0 ? { schema: input, state: 'mismatch', issues } : { schema: outputSchema(input, config), state: 'confirmed', issues: [] }; },
  execute(inputs, config): Table { const input = inputs[0]; if (input === undefined) throw new ConfigError('outlier-filter requires one input'); requireColumns(input.schema, config.groupBy, 'outlier-filter'); requireNumbers(input.schema, config.columns, 'outlier-filter');
    const grouped = new Map<string, Row[]>(); for (const row of input.rows) { const key = groupKey(row, config.groupBy); const current = grouped.get(key); if (current === undefined) grouped.set(key, [row]); else current.push(row); }
    const limits = new Map<string, Map<string, Bounds | undefined>>(); for (const [key, rows] of grouped) { const byColumn = new Map<string, Bounds | undefined>(); for (const column of config.columns) byColumn.set(column, bounds(rows.map((row) => row[column]).filter((value): value is number => typeof value === 'number' && Number.isFinite(value)), config)); limits.set(key, byColumn); }
    const rows: Row[] = []; for (const row of input.rows) { const reasons: string[] = []; let score: number | null = null; let missing = false; const byColumn = limits.get(groupKey(row, config.groupBy))!; for (const column of config.columns) { const value = row[column]; if (typeof value !== 'number' || !Number.isFinite(value)) { missing = true; continue; } const limit = byColumn.get(column); if (limit === undefined) continue; const isOutlier = config.method === 'iqr' ? value < limit.low || value > limit.high : limit.scale !== 0 && Math.abs((value - limit.center) / limit.scale) > config.threshold; if (isOutlier) { const currentScore = config.method === 'iqr' ? Math.max(limit.low - value, value - limit.high) : Math.abs((value - limit.center) / limit.scale); score = score === null ? currentScore : Math.max(score, currentScore); reasons.push(column); } }
      const marked = reasons.length > 0 || (missing && config.nulls === 'exclude'); if (config.action === 'exclude') { if (!marked) rows.push(row); } else rows.push({ ...row, [config.flagColumns.isOutlier]: marked, [config.flagColumns.score]: score, [config.flagColumns.reason]: reasons.length > 0 ? reasons.join(', ') : missing && config.nulls === 'exclude' ? 'null' : null }); }
    return { schema: outputSchema(input.schema, config), rows }; },
};
