import { z } from 'zod';
import type { Row, Schema, Table } from '../../data/types';
import { ConfigError, SchemaError } from '../errors';
import type { EtlNode, SchemaInference, SchemaIssue } from '../node';
import { zodMessage } from './zod-error';
import { existingColumns, groupKey, groupValues, numericColumns, requireColumns, requireNumbers } from './analysis-utils';
import { findColumn } from '../../data/schema';

export interface TimeSeriesAnalysisConfig { readonly configVersion: 1; readonly timeColumn: string; readonly valueColumns: readonly string[]; readonly groupBy: readonly string[]; readonly timezone: string; readonly interval: 'minute' | 'hour' | 'day' | 'week' | 'month'; readonly aggregate: 'count' | 'sum' | 'mean' | 'min' | 'max'; readonly fill: 'none' | 'zero' | 'forward'; readonly window?: { readonly operation: 'moving-mean' | 'moving-sum'; readonly size: number }; readonly comparison?: { readonly lag: number; readonly output: readonly ('delta' | 'percent-change')[] }; }
const configSchema = z.object({ configVersion: z.literal(1).default(1), timeColumn: z.string().min(1), valueColumns: z.array(z.string().min(1)).min(1).max(10), groupBy: z.array(z.string().min(1)).default([]), timezone: z.string().min(1).default('UTC'), interval: z.enum(['minute', 'hour', 'day', 'week', 'month']).default('day'), aggregate: z.enum(['count', 'sum', 'mean', 'min', 'max']).default('mean'), fill: z.enum(['none', 'zero', 'forward']).default('none'), window: z.object({ operation: z.enum(['moving-mean', 'moving-sum']), size: z.number().int().min(2).max(1000) }).optional(), comparison: z.object({ lag: z.number().int().min(1).max(1000), output: z.array(z.enum(['delta', 'percent-change'])).min(1) }).optional() });
function validate(config: unknown): TimeSeriesAnalysisConfig { const parsed = configSchema.safeParse(config); if (!parsed.success) throw new ConfigError(`time-series-analysis: invalid config: ${zodMessage(parsed.error)}`); return parsed.data; }
function outputSchema(input: Schema, config: TimeSeriesAnalysisConfig): Schema { return { columns: [...config.groupBy.map((name) => input.columns.find((column) => column.name === name)!), { name: 'bucketStart', type: 'date', nullable: false }, { name: 'series', type: 'string', nullable: false }, { name: 'value', type: 'number', nullable: true }, { name: 'sampleCount', type: 'number', nullable: false }, ...(config.window === undefined ? [] : [{ name: 'movingValue', type: 'number' as const, nullable: true }]), ...(config.comparison?.output.includes('delta') === true ? [{ name: 'delta', type: 'number' as const, nullable: true }] : []), ...(config.comparison?.output.includes('percent-change') === true ? [{ name: 'percentChange', type: 'number' as const, nullable: true }] : [])] }; }
interface ZonedParts { readonly year: number; readonly month: number; readonly day: number; readonly hour: number; readonly minute: number; readonly weekday: number }
const WEEKDAYS: Readonly<Record<string, number>> = { Sun: 0, Mon: 1, Tue: 2, Wed: 3, Thu: 4, Fri: 5, Sat: 6 };
/**
 * timezone ごとの `Intl.DateTimeFormat` キャッシュ。
 * 生成コストが支配的なため、行ごとに new すると5万行で数秒かかる（モジュールスコープで再利用する）。
 */
const formatters = new Map<string, Intl.DateTimeFormat>();
/** timezone が有効かの判定結果キャッシュ（無効な timezone は生成時に RangeError になる）。 */
const zoneSupport = new Map<string, boolean>();
function formatterFor(timezone: string): Intl.DateTimeFormat {
  const cached = formatters.get(timezone);
  if (cached !== undefined) return cached;
  const created = new Intl.DateTimeFormat('en-US', { timeZone: timezone, year: 'numeric', month: 'numeric', day: 'numeric', hour: 'numeric', minute: 'numeric', hourCycle: 'h23', weekday: 'short' });
  formatters.set(timezone, created);
  return created;
}
function zoneSupported(timezone: string): boolean { const cached = zoneSupport.get(timezone); if (cached !== undefined) return cached; let supported: boolean; try { formatterFor(timezone).format(); supported = true; } catch { supported = false; } zoneSupport.set(timezone, supported); return supported; }
function partsAt(value: Date, timezone: string): ZonedParts { const result: Record<string, string> = {}; for (const part of formatterFor(timezone).formatToParts(value)) if (part.type !== 'literal') result[part.type] = part.value; return { year: Number(result.year), month: Number(result.month), day: Number(result.day), hour: Number(result.hour), minute: Number(result.minute), weekday: WEEKDAYS[result.weekday ?? 'Sun'] ?? 0 }; }
function asUtc(parts: Omit<ZonedParts, 'weekday'>): number { return Date.UTC(parts.year, parts.month - 1, parts.day, parts.hour, parts.minute); }
/** ローカル暦時刻をIANA timezoneの実際のinstantへ戻す。DST境界でoffsetが変わるため収束計算する。 */
function zonedDate(parts: Omit<ZonedParts, 'weekday'>, timezone: string): Date { const target = asUtc(parts); let instant = target; for (let attempt = 0; attempt < 4; attempt++) { const actual = partsAt(new Date(instant), timezone); const offset = asUtc(actual) - instant; const next = target - offset; if (next === instant) break; instant = next; } return new Date(instant); }
function bucket(value: Date, interval: TimeSeriesAnalysisConfig['interval'], timezone: string): Date { const local = partsAt(value, timezone); let { year, month, day, hour, minute } = local; if (interval !== 'minute') minute = 0; if (interval !== 'hour') hour = 0; if (interval === 'week') { const calendar = new Date(Date.UTC(year, month - 1, day - ((local.weekday + 6) % 7))); year = calendar.getUTCFullYear(); month = calendar.getUTCMonth() + 1; day = calendar.getUTCDate(); } if (interval === 'month') day = 1; return zonedDate({ year, month, day, hour, minute }, timezone); }
function nextBucket(value: Date, interval: TimeSeriesAnalysisConfig['interval'], timezone: string): Date { const local = partsAt(value, timezone); const calendar = new Date(Date.UTC(local.year, local.month - 1, local.day, local.hour, local.minute)); if (interval === 'minute') calendar.setUTCMinutes(calendar.getUTCMinutes() + 1); else if (interval === 'hour') calendar.setUTCHours(calendar.getUTCHours() + 1); else if (interval === 'day') calendar.setUTCDate(calendar.getUTCDate() + 1); else if (interval === 'week') calendar.setUTCDate(calendar.getUTCDate() + 7); else calendar.setUTCMonth(calendar.getUTCMonth() + 1, 1); return zonedDate({ year: calendar.getUTCFullYear(), month: calendar.getUTCMonth() + 1, day: calendar.getUTCDate(), hour: calendar.getUTCHours(), minute: calendar.getUTCMinutes() }, timezone); }
export const timeSeriesAnalysisNode: EtlNode<TimeSeriesAnalysisConfig> = {
  type: 'time-series-analysis', kind: 'analyze', inputArity: 1, validateConfig: validate,
  inferSchema(inputs, config): SchemaInference { const input = inputs[0] ?? { columns: [] }; const time = findColumn(input, config.timeColumn); const issues: SchemaIssue[] = [...existingColumns(input, config.groupBy, 'time-series-analysis'), ...numericColumns(input, config.valueColumns, 'time-series-analysis')]; if (time === undefined) issues.push({ severity: 'error', message: `time-series-analysis: column not found: ${config.timeColumn}`, column: config.timeColumn }); else if (time.type !== 'date') issues.push({ severity: 'error', message: `time-series-analysis: column '${config.timeColumn}' must be date`, column: config.timeColumn }); if (!zoneSupported(config.timezone)) issues.push({ severity: 'error', message: `time-series-analysis: unsupported IANA timezone: ${config.timezone}` }); return issues.some((issue) => issue.severity === 'error') ? { schema: input, state: 'mismatch', issues } : { schema: outputSchema(input, config), state: 'confirmed', issues }; },
  execute(inputs, config): Table { const input = inputs[0]; if (input === undefined) throw new ConfigError('time-series-analysis requires one input'); requireColumns(input.schema, [config.timeColumn, ...config.groupBy], 'time-series-analysis'); requireNumbers(input.schema, config.valueColumns, 'time-series-analysis'); if (findColumn(input.schema, config.timeColumn)?.type !== 'date') throw new SchemaError(`time-series-analysis: column '${config.timeColumn}' must be date`); if (!zoneSupported(config.timezone)) throw new ConfigError(`time-series-analysis: unsupported IANA timezone: ${config.timezone}`);
    // bucket / nextBucket は Intl の parts 取得を伴うため、同一 instant の結果を実行内で再利用する。
    const bucketCache = new Map<number, Date>(); const nextCache = new Map<number, Date>();
    const bucketOf = (value: Date): Date => { const time = value.getTime(); const cached = bucketCache.get(time); if (cached !== undefined) return cached; const computed = bucket(value, config.interval, config.timezone); bucketCache.set(time, computed); return computed; };
    const nextOf = (value: Date): Date => { const time = value.getTime(); const cached = nextCache.get(time); if (cached !== undefined) return cached; const computed = nextBucket(value, config.interval, config.timezone); nextCache.set(time, computed); return computed; };
    const grouped = new Map<string, { group: Row; date: Date; series: string; values: number[] }>(); for (const row of input.rows) { const date = row[config.timeColumn]; if (!(date instanceof Date) || Number.isNaN(date.getTime())) continue; const b = bucketOf(date); const bucketIso = b.toISOString(); const rowKey = groupKey(row, config.groupBy); for (const series of config.valueColumns) { const value = row[series]; if (typeof value !== 'number' || !Number.isFinite(value)) continue; const key = `${rowKey}|${series}|${bucketIso}`; const current = grouped.get(key); if (current === undefined) grouped.set(key, { group: groupValues(row, config.groupBy), date: b, series, values: [value] }); else current.values.push(value); } }
    const rows: Row[] = [...grouped.values()].map((entry) => { const value = entry.values.length === 0 ? null : config.aggregate === 'count' ? entry.values.length : config.aggregate === 'sum' ? entry.values.reduce((sum, item) => sum + item, 0) : config.aggregate === 'mean' ? entry.values.reduce((sum, item) => sum + item, 0) / entry.values.length : config.aggregate === 'min' ? entry.values.reduce((low, item) => item < low ? item : low) : entry.values.reduce((high, item) => item > high ? item : high); return { ...entry.group, bucketStart: entry.date, series: entry.series, value, sampleCount: entry.values.length }; }).sort((a, b) => (a.bucketStart as Date).getTime() - (b.bucketStart as Date).getTime());
    const partitions = new Map<string, Row[]>(); for (const row of rows) { const key = `${groupKey(row, config.groupBy)}|${row.series}`; const current = partitions.get(key); if (current === undefined) partitions.set(key, [row]); else current.push(row); }
    const completed: Row[] = [];
    for (const values of partitions.values()) {
      values.sort((a, b) => (a.bucketStart as Date).getTime() - (b.bucketStart as Date).getTime());
      if (config.fill === 'none') { completed.push(...values); continue; }
      const byTime = new Map(values.map((row) => [(row.bucketStart as Date).getTime(), row])); const first = values[0]!; const last = values[values.length - 1]!; let cursor = first.bucketStart as Date; let previous: number | null = null;
      while (cursor.getTime() <= (last.bucketStart as Date).getTime()) { const existing = byTime.get(cursor.getTime()); if (existing !== undefined) { completed.push(existing); previous = typeof existing.value === 'number' ? existing.value : previous; } else { const value = config.fill === 'zero' ? 0 : previous; completed.push({ ...Object.fromEntries(config.groupBy.map((column) => [column, first[column] ?? null])), bucketStart: cursor, series: first.series as string, value, sampleCount: 0 }); } cursor = nextOf(cursor); }
    }
    const completedPartitions = new Map<string, Row[]>(); for (const row of completed) { const key = `${groupKey(row, config.groupBy)}|${row.series}`; const current = completedPartitions.get(key); if (current === undefined) completedPartitions.set(key, [row]); else current.push(row); } for (const values of completedPartitions.values()) values.forEach((row, index) => { const value = row.value as number | null; if (config.window !== undefined) { const window = values.slice(Math.max(0, index - config.window.size + 1), index + 1).map((candidate) => candidate.value).filter((candidate): candidate is number => typeof candidate === 'number'); (row as Record<string, unknown>).movingValue = window.length === 0 ? null : config.window.operation === 'moving-sum' ? window.reduce((sum, item) => sum + item, 0) : window.reduce((sum, item) => sum + item, 0) / window.length; } const lag = config.comparison === undefined ? undefined : values[index - config.comparison.lag]?.value; if (config.comparison?.output.includes('delta') === true) (row as Record<string, unknown>).delta = typeof value === 'number' && typeof lag === 'number' ? value - lag : null; if (config.comparison?.output.includes('percent-change') === true) (row as Record<string, unknown>).percentChange = typeof value === 'number' && typeof lag === 'number' && lag !== 0 ? (value - lag) / Math.abs(lag) : null; });
    return { schema: outputSchema(input.schema, config), rows: completed.sort((a, b) => (a.bucketStart as Date).getTime() - (b.bucketStart as Date).getTime()) }; },
};
