import { SqliteRepositoryBase, type SqliteDatabaseSource } from './sqlite-database';
import { QualityGateConflictError, QualityGateNotFoundError } from '../../domain/evaluation/errors';
import type { GatePolicySummary, QualityGateRepository } from '../../domain/evaluation/quality-gate-repository';
import { deserializeGatePolicy, deserializeGateReport, deserializePromotionRequest, serializeGatePolicy, serializeGateReport, serializePromotionRequest } from '../../domain/evaluation/quality-gate-serialization';
import type { GatePolicy, GateReport, PromotionRequest } from '../../domain/evaluation/quality-gate';
import type { TenantScope } from '../../domain/tool/ids';
import { SemVer } from '../../domain/tool/semver';

const isUnique = (error: unknown): boolean => error instanceof Error && error.message.includes('UNIQUE constraint failed');

export class SqliteQualityGateRepository extends SqliteRepositoryBase implements QualityGateRepository {
  constructor(source: SqliteDatabaseSource = ':memory:') {
    super(source);
  }
  async savePolicy(policy: GatePolicy): Promise<void> { const { tenant, internalId, version } = policy.metadata; try { this.db.prepare(`INSERT INTO gate_policies (tenant_id,workspace_id,internal_id,version,major,minor,patch,record_json) VALUES (?,?,?,?,?,?,?,?)`).run(tenant.tenantId, tenant.workspaceId, internalId, version.toString(), version.major, version.minor, version.patch, JSON.stringify(serializeGatePolicy(policy))); } catch (error) { if (isUnique(error)) throw new QualityGateConflictError(`Gate policy version already exists: ${internalId}@${version.toString()}`); throw error; } }
  async findPolicyVersion(scope: TenantScope, internalId: string, version: SemVer): Promise<GatePolicy | null> { const row = this.db.prepare(`SELECT record_json FROM gate_policies WHERE tenant_id=? AND workspace_id=? AND internal_id=? AND version=?`).get(scope.tenantId, scope.workspaceId, internalId, version.toString()); return row === undefined ? null : deserializeGatePolicy(JSON.parse(String(row['record_json']))); }
  async findLatestPolicy(scope: TenantScope, internalId: string): Promise<GatePolicy | null> { const row = this.db.prepare(`SELECT record_json FROM gate_policies WHERE tenant_id=? AND workspace_id=? AND internal_id=? AND deleted=0 ORDER BY major DESC,minor DESC,patch DESC LIMIT 1`).get(scope.tenantId, scope.workspaceId, internalId); return row === undefined ? null : deserializeGatePolicy(JSON.parse(String(row['record_json']))); }
  async listPolicyVersions(scope: TenantScope, internalId: string): Promise<SemVer[]> { return this.db.prepare(`SELECT major,minor,patch FROM gate_policies WHERE tenant_id=? AND workspace_id=? AND internal_id=? AND deleted=0 ORDER BY major,minor,patch`).all(scope.tenantId, scope.workspaceId, internalId).map((row) => SemVer.of(Number(row['major']), Number(row['minor']), Number(row['patch']))); }
  async listPolicies(scope: TenantScope): Promise<GatePolicySummary[]> { return this.db.prepare(`SELECT p.record_json FROM gate_policies p WHERE p.tenant_id=? AND p.workspace_id=? AND p.deleted=0 AND p.version=(SELECT x.version FROM gate_policies x WHERE x.tenant_id=p.tenant_id AND x.workspace_id=p.workspace_id AND x.internal_id=p.internal_id AND x.deleted=0 ORDER BY x.major DESC,x.minor DESC,x.patch DESC LIMIT 1) ORDER BY p.internal_id`).all(scope.tenantId, scope.workspaceId).map((row) => { const policy = deserializeGatePolicy(JSON.parse(String(row['record_json']))); return { internalId: policy.metadata.internalId, displayName: policy.metadata.displayName, publishName: policy.metadata.publishName, latestVersion: policy.metadata.version, state: policy.metadata.state, ruleCount: policy.rules.length }; }); }
  async deletePolicy(scope: TenantScope, internalId: string): Promise<boolean> {
    const existing = this.db.prepare(`SELECT 1 FROM gate_policies WHERE tenant_id=? AND workspace_id=? AND internal_id=? AND deleted=0 LIMIT 1`).get(scope.tenantId, scope.workspaceId, internalId);
    if (existing === undefined) return false;
    this.db.prepare(`UPDATE gate_policies SET deleted=1 WHERE tenant_id=? AND workspace_id=? AND internal_id=?`).run(scope.tenantId, scope.workspaceId, internalId);
    return true;
  }
  async saveReport(report: GateReport): Promise<void> { try { this.db.prepare(`INSERT INTO gate_reports (tenant_id,workspace_id,report_id,candidate_experiment_id,created_at,record_json) VALUES (?,?,?,?,?,?)`).run(report.scope.tenantId, report.scope.workspaceId, report.id, report.candidateExperimentId, report.createdAt, JSON.stringify(serializeGateReport(report))); } catch (error) { if (isUnique(error)) throw new QualityGateConflictError(`Gate report already exists: ${report.id}`); throw error; } }
  async findReport(scope: TenantScope, id: string): Promise<GateReport | null> { const row = this.db.prepare(`SELECT record_json FROM gate_reports WHERE tenant_id=? AND workspace_id=? AND report_id=?`).get(scope.tenantId, scope.workspaceId, id); return row === undefined ? null : deserializeGateReport(JSON.parse(String(row['record_json']))); }
  async listReports(scope: TenantScope, candidateExperimentId?: string): Promise<GateReport[]> { const rows = candidateExperimentId === undefined ? this.db.prepare(`SELECT record_json FROM gate_reports WHERE tenant_id=? AND workspace_id=? ORDER BY created_at DESC`).all(scope.tenantId, scope.workspaceId) : this.db.prepare(`SELECT record_json FROM gate_reports WHERE tenant_id=? AND workspace_id=? AND candidate_experiment_id=? ORDER BY created_at DESC`).all(scope.tenantId, scope.workspaceId, candidateExperimentId); return rows.map((row) => deserializeGateReport(JSON.parse(String(row['record_json'])))); }
  async createPromotion(request: PromotionRequest): Promise<void> { try { this.db.prepare(`INSERT INTO promotion_requests (tenant_id,workspace_id,request_id,agent_id,requested_at,record_json) VALUES (?,?,?,?,?,?)`).run(request.scope.tenantId, request.scope.workspaceId, request.id, request.agent.id, request.requestedAt, JSON.stringify(serializePromotionRequest(request))); } catch (error) { if (isUnique(error)) throw new QualityGateConflictError(`Promotion request already exists: ${request.id}`); throw error; } }
  async updatePromotion(request: PromotionRequest): Promise<void> { const result = this.db.prepare(`UPDATE promotion_requests SET record_json=? WHERE tenant_id=? AND workspace_id=? AND request_id=?`).run(JSON.stringify(serializePromotionRequest(request)), request.scope.tenantId, request.scope.workspaceId, request.id); if (Number(result.changes) === 0) throw new QualityGateNotFoundError(`Promotion request not found: ${request.id}`); }
  async findPromotion(scope: TenantScope, id: string): Promise<PromotionRequest | null> { const row = this.db.prepare(`SELECT record_json FROM promotion_requests WHERE tenant_id=? AND workspace_id=? AND request_id=?`).get(scope.tenantId, scope.workspaceId, id); return row === undefined ? null : deserializePromotionRequest(JSON.parse(String(row['record_json']))); }
  async listPromotions(scope: TenantScope, agentId?: string): Promise<PromotionRequest[]> { const rows = agentId === undefined ? this.db.prepare(`SELECT record_json FROM promotion_requests WHERE tenant_id=? AND workspace_id=? ORDER BY requested_at DESC`).all(scope.tenantId, scope.workspaceId) : this.db.prepare(`SELECT record_json FROM promotion_requests WHERE tenant_id=? AND workspace_id=? AND agent_id=? ORDER BY requested_at DESC`).all(scope.tenantId, scope.workspaceId, agentId); return rows.map((row) => deserializePromotionRequest(JSON.parse(String(row['record_json'])))); }
}
