import { useCallback, useEffect, useState } from 'react';
import type { ToolApiClient } from '../api/tool-api';
import { useI18n } from '../i18n';

export function SettingsPage({ client }: { readonly client: ToolApiClient }) {
  const [health, setHealth] = useState<'checking' | 'ok' | 'offline'>('checking');
  const { language, setLanguage, text } = useI18n();
  const refresh = useCallback(async () => { setHealth('checking'); try { await client.health(); setHealth('ok'); } catch { setHealth('offline'); } }, [client]);
  useEffect(() => { void refresh(); }, [refresh]);
  const healthLabel = health === 'checking' ? text('checking', '確認中') : health === 'ok' ? text('ok', '正常') : text('offline', 'オフライン');
  return <main className="workspace-page"><header className="workspace-header"><div><span className="eyebrow">{text('Settings', '設定')}</span><h1>{text('Runtime settings', '実行環境設定')}</h1><p>{text('Review the local runtime and its safety boundaries.', 'ローカル実行環境と安全境界を確認します。')}</p></div><button type="button" className="secondary" onClick={() => void refresh()}>{text('Refresh status', '状態を更新')}</button></header><div className="settings-grid"><section className="workspace-card"><h2>{text('Language', '言語')}</h2><label>{text('Display language', '表示言語')}<select aria-label="Language" value={language} onChange={(event) => setLanguage(event.target.value as 'en' | 'ja')}><option value="en">English</option><option value="ja">日本語</option></select></label><p className="empty-state">{text('The selection is saved in this browser.', '選択内容はこのブラウザに保存されます。')}</p></section><section className="workspace-card"><h2>{text('Connection', '接続')}</h2><dl className="settings-list"><div><dt>API</dt><dd><span className={`health-dot ${health}`} />{healthLabel}</dd></div><div><dt>{text('Scope', 'スコープ')}</dt><dd><code>local / default</code></dd></div><div><dt>{text('Mode', 'モード')}</dt><dd><code>LOCAL · PREVIEW</code></dd></div></dl></section><section className="workspace-card"><h2>{text('Model provider', 'モデルプロバイダー')}</h2><dl className="settings-list"><div><dt>{text('Provider', 'プロバイダー')}</dt><dd>LM Studio · OpenAI compatible</dd></div><div><dt>{text('Endpoint', 'エンドポイント')}</dt><dd><code>LM_STUDIO_BASE_URL</code></dd></div><div><dt>{text('Model', 'モデル')}</dt><dd><code>LM_STUDIO_MODEL</code></dd></div><div><dt>{text('Timeout', 'タイムアウト')}</dt><dd><code>LM_STUDIO_TIMEOUT_MS</code></dd></div></dl><p className="empty-state">{text('Server-side environment variables are intentionally not editable from the browser.', 'サーバー側の環境変数はブラウザから変更できません。')}</p></section><section className="workspace-card"><h2>{text('Security gates', '安全ゲート')}</h2><ul className="gate-list"><li className="ready">{text('Preview blocks write Tools', 'プレビューでは書き込みToolを遮断')}</li><li className="ready">{text('Run trace persistence enabled', '実行トレースの永続化が有効')}</li><li className="locked">{text('MCP publication locked until auth/audit adapters exist', '認証・監査アダプター実装までMCP公開をロック')}</li><li className="locked">{text('Production execution unavailable', '本番実行は利用不可')}</li></ul></section></div></main>;
}
